using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;
using RestaurantSoftware.DA_Layer;
using RestaurantSoftware.Utils;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_ThanhToan : DevExpress.XtraEditors.XtraForm
    {
        DataTable dt = new DataTable();
        private Ban_BLL _banBll = new Ban_BLL();
        private HoaDon_BLL _hoadonBll = new HoaDon_BLL();
        private ThanhToan_BLL _thanhToanBll = new ThanhToan_BLL();
        private List<int> _listUpdate = new List<int>();


        public Frm_ThanhToan()
        {
            InitializeComponent();
            dt_NgayLap.Text = DateTime.Now.ToShortDateString();
            btn_inhoadon.Enabled = false;
            // This line of code is generated by Data Source Configuration Wizard
            cmb_NhanVien.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().NhanViens;
        }


        private void Frm_ThanhToan_Load(object sender, EventArgs e)
        {
            LoadDataSource();

        }
        private void LoadDataSource()
        {
            LoadDsBan();
            _thanhToanBll.LoadHoaDon(grv_HoaDon);
        }
        public void LoadDsBan()
        {
            lvDsBan.Clear();
            DataTable ban = Utils.Utils.ConvertToDataTable<ChiTiet_ThanhToan>(_thanhToanBll.LayDanhSachBan("chưa thanh toán"));

            lvDsBan.LargeImageList = imageList1;

            foreach (DataRow dr in ban.Rows)
            {
                bool exsistGroup = false;
                ListViewItem lvItem = new ListViewItem();
                ListViewGroup lvGroup = new ListViewGroup();
                lvItem.Text = dr["tenban"].ToString();
                switch (dr["trangthai"].ToString())
                {
                    case "trống":
                        lvItem.ImageIndex = 2;
                        break;
                    case "đặt trước":
                        lvItem.ImageIndex = 1;
                        break;
                    case "đầy":
                        lvItem.ImageIndex = 0;
                        break;
                }
                lvItem.Name = dr["Idban"].ToString();
                lvGroup.Header = dr["Tenloaiban"].ToString();
                lvItem.Group = lvGroup;

                if (lvDsBan.Groups.Count != 0)
                {
                    foreach (ListViewGroup gr in lvDsBan.Groups)
                    {
                        if (gr.Header == lvGroup.Header)
                        {
                            exsistGroup = true;
                            lvItem.Group = gr;
                            break;
                        }
                    }
                    if (exsistGroup == false)
                    {
                        lvDsBan.Groups.Add(lvGroup);
                    }

                }
                else lvDsBan.Groups.Add(lvGroup);
                lvDsBan.Items.Add(lvItem);

            }
        }

        private void lvDsBan_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (lvDsBan.SelectedItems.Count > 0)
            {
                txt_Ban.Text = lvDsBan.SelectedItems[0].Text;

                _thanhToanBll.loadid(int.Parse(lvDsBan.SelectedItems[0].Name), "chưa thanh toán", txt_MaHoaDon, cmb_NhanVien, dt_NgayLap);
                LoadChiTietHoaDon();
                btn_inhoadon.Enabled = false;
                btn_TamTinh.Enabled = true;
                btn_ThanhToan.Enabled = true;

            }
        }
        public void LoadChiTietHoaDon()
        {
            try
            {
                int a = int.Parse(txt_MaHoaDon.Text);
                _thanhToanBll.LoadChiTietHoaDon(a, grd_DanhSachMon);
            }
            catch (Exception)
            {
                Notifications.Answers("");
            }
            
        }

        private void gv_HoaDon_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) =="đã thanh toán")
            {
                btn_inhoadon.Enabled = true;
                btn_TamTinh.Enabled = false;
                btn_ThanhToan.Enabled = false;
            }
            else
                if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) =="chưa thanh toán")
                {
                    txt_Ban.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_TenBan);
                    _thanhToanBll.loadid(int.Parse(gv_HoaDon.GetFocusedRowCellDisplayText(col_MaBan)), "chưa thanh toán", txt_MaHoaDon, cmb_NhanVien, dt_NgayLap);
                    LoadChiTietHoaDon();
                    btn_inhoadon.Enabled = false;
                    btn_TamTinh.Enabled = true;
                    btn_ThanhToan.Enabled = true;
                }
        }
    }
}