using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_QuanLyNhapHang : DevExpress.XtraEditors.XtraForm
    {
        DataTable dt = null;
        NhapHang_BLL _hdBLL;
        public Frm_QuanLyNhapHang()
        {
            InitializeComponent();
            dt = new DataTable();
            _hdBLL = new NhapHang_BLL();

            LoadDanhSachPhieuNhap();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().HangHoas;
            _hdBLL.LayThongTinHangHoa(gridControl1);
        }
        public void LoadDanhSachPhieuNhap()
        {
            _hdBLL.LayDanhSachPhieuNhap(gridControl3);
        }
        private void Frm_QuanLyNhapHang_Load(object sender, EventArgs e)
        {

        }
    }
}